<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DNS" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Missions\fob\" />
    <Folder Include="Missions\base\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="inFAMOUSReborn.Launcher\**" />
    <EmbeddedResource Remove="inFAMOUSReborn.Launcher\**" />
    <None Remove="inFAMOUSReborn.Launcher\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="infamous.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
</Project>
